### ISSUE TITLE
Create relaton-data-ccsds

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-data-ccsds#1]
Needed for https://github.com/relaton/relaton-ccsds/issues/1

**Comment by ronaldtse** [comment]
Updated access permissions. Thank you @andrew2net ! Feel free to close when ready.

**Comment by andrew2net** [comment]
@ronaldtse shouldn't we merge translations into single documents? For example merge:
- [CCSDS 551.1-O-2](https://public.ccsds.org/Pubs/551x1o2e2.pdf) and [CCSDS 551.1-O-2 - Russian Translated](https://public.ccsds.org/Pubs/551x1o2e1(R).pdf)
- [CCSDS 650.0-M-2](https://public.ccsds.org/Pubs/650x0m2.pdf) and [CCSDS 650.0-M-2 - French Translated](https://public.ccsds.org/Pubs/650x0m2(F).pdf)

**Comment by ronaldtse** [comment]
@andrew2net I think we're facing more of these like those from NIST.

1. There should be a language-independent entry for citation
2. There should be a language-specific entry for citation

Ping @opoudjis for thoughts.

**Comment by opoudjis** [comment]
As already discussed with you @ronaldtse, we have already had to deal with this kind of issue with undated references.

We have specific editions of standards (Expressions), which have a date, and then we have an abstraction over all those dated versions, which is the undated standard; the relation between the two is hasInstance/isInstanceOf. 

Similarly, we have language-specific versions of standards, and then we have a language-independent abstraction over all those language-specific versions. They too are related with hasInstance/isInstanceOf.

So, assume CCSDS-1-EN, CCSDS-1-RU, and the language-independent CCSDS-1-ALL. Furthermore, assume that we don't mind saying that one of these versions (EN, surprise surprise) was written first, and the others are translated from it.

* CCSDS-1-ALL
  * hasInstance: CCSDS-1-EN
  * hasInstance: CCSDS-1-RU

* CCSDS-1-EN
  * isInstanceOf: CCSDS-1-ALL
  * hasTranslation: CCSDS-1-RU

* CCSDS-1-RU
  * isInstanceOf: CCSDS-1-ALL
  * isTranslationOf: CCSDS-1-EN

**Comment by ronaldtse** [comment]
Actually we already have this issue for ISO, since many publications are bilingual (EN, FR) and some trilingual (EN, FR, RU). Relaton-ISO already supports citation of instances of all three languages. We should apply the same solution across all flavors.

@andrew2net can you please help? We should also document this method of modeling on Relaton.org.

**Comment by opoudjis** [comment]
@ronaldtse  : https://github.com/relaton/relaton.github.io/pull/49

**Comment by andrew2net** [comment]
@ronaldtse actually relaton-iso doesn't support language-specific citations. The ISO language-specific pages use JS heavily. I tried to get data from the pages but had to switch to other urgent tasks.

**Comment by andrew2net** [comment]
> CCSDS-1-EN
> 
> * isInstanceOf: CCSDS-1-ALL

@opoudjis do you mean "instance: CCSDS-1-ALL". There is no "isInstanceOf" in the grammar.

**Comment by ronaldtse** [comment]
We probably should update the grammar. I'm not sure if anyone uses "instance" today.

**Comment by andrew2net** [comment]
@ronaldtse we use the `instance` relation type in all parts documents:
```sh
$  relaton fetch 'ISO 19115 (all parts)'
[relaton-iso] (ISO 19115) Fetching from ISO...
[relaton-iso] (ISO 19115) Found `ISO 19115`.
<bibdata type="standard" schema-version="v1.2.3">
  <fetched>2023-08-29</fetched>
  <title type="title-intro" format="text/plain" language="en" script="Latn">Geographic information</title>
  <title type="title-main" format="text/plain" language="en" script="Latn">Metadata</title>
  <title type="main" format="text/plain" language="en" script="Latn">Geographic information – Metadata</title>
  <title type="title-intro" format="text/plain" language="fr" script="Latn">Information géographique</title>
  <title type="title-main" format="text/plain" language="fr" script="Latn">Métadonnées</title>
  <title type="main" format="text/plain" language="fr" script="Latn">Information géographique – Métadonnées</title>
  <uri type="src">https://www.iso.org/standard/53798.html</uri>
  <uri type="obp">https://www.iso.org/obp/ui/en/#!iso:std:53798:en</uri>
  <uri type="rss">https://www.iso.org/contents/data/standard/05/37/53798.detail.rss</uri>
  <docidentifier type="ISO" primary="true">ISO 19115 (all parts)</docidentifier>
  ...
  <relation type="instance">
    <bibitem type="standard">
      <fetched>2023-08-29</fetched>
      <title type="title-intro" format="text/plain" language="en" script="Latn">Geographic information</title>
      <title type="title-main" format="text/plain" language="en" script="Latn">Metadata</title>
      <title type="title-part" format="text/plain" language="en" script="Latn">Part 1: Fundamentals</title>
      <title type="main" format="text/plain" language="en" script="Latn">Geographic information - Metadata - Part 1: Fundamentals</title>
      <title type="title-intro" format="text/plain" language="fr" script="Latn">Information géographique</title>
      <title type="title-main" format="text/plain" language="fr" script="Latn">Métadonnées</title>
      <title type="title-part" format="text/plain" language="fr" script="Latn">Partie 1: Principes de base</title>
      <title type="main" format="text/plain" language="fr" script="Latn">Information géographique - Métadonnées - Partie 1: Principes de base</title>
      <uri type="src">https://www.iso.org/standard/53798.html</uri>
      <uri type="obp">https://www.iso.org/obp/ui/en/#!iso:std:53798:en</uri>
      <uri type="rss">https://www.iso.org/contents/data/standard/05/37/53798.detail.rss</uri>
      <docidentifier type="ISO" primary="true">ISO 19115-1:2014</docidentifier>
      ...
```

**Comment by ronaldtse** [comment]
Does anyone use those relations right now? If not we should align the grammar with the model.

**Comment by opoudjis** [comment]
I mean, *we* do.

The grammar does indeed have:

"instance" |  
"hasInstance" | 

and I'd misremembered. Therefore, https://www.relaton.org/specs/model/relations/ is wrong. I'll go through and debug them. Ronald, there's already a pending PR for you.

**Comment by opoudjis** [comment]
... OTOH, maybe we do change the grammar and implementation after all, if it is needlessly inconsistent.

The discrepancies are (model vs grammar);

* instanceOf / instance 
* adapted / adaptedFrom

...

I suggest we change the grammar and implementation, to use instanceOf, and the model, to use adaptedFrom. That makes it clearer and more consistent.

Let me know if you object?

**Comment by ronaldtse** [comment]
I fully agree with these two changes. Any other changes to make?

**Comment by opoudjis** [comment]
None that I can detect.

I'm sorry, @andrew2net , but that does mean replacing "instance" with "instanceOf" everywhere, for consistency with the rest of the model. I also need to change some of my code.

**Comment by andrew2net** [comment]
Translated relation updated:
- [CCSDS 650.0-B-1 - French Translated](https://github.com/relaton/relaton-data-ccsds/blob/6ae2fa92cec1f4d0ff4cce9648e01eb4c7e13f0c/data/CCSDS-650-0-B-1-French-Translated.yaml#L45)
- [CCSDS 650.0-B-1](https://github.com/relaton/relaton-data-ccsds/blob/6ae2fa92cec1f4d0ff4cce9648e01eb4c7e13f0c/data/CCSDS-650-0-B-1.yaml#L58)
