### ISSUE TITLE
Generate additional references for Silver Books / Retired publications

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-ccsds#9]
In CCSDS publications, the publication identifiers change when a document is superseded.

While it is useful for knowing what is current, this will break older document citations. For example, if I have a document that points to "CCSDS 720.1-G-3", I can't find it anymore after it retires and becomes "CCSDS 720.1-G-3-S".

This means that in our repository we need to generate the older issues as well for all Silver Books (CCSDS calls retired publications "Silver Books").

Given "CCSDS 720.1-G-3-S", we have to generate:
* CCSDS 720.1-G-3-S
* CCSDS 720.1-G-3

Given "CCSDS 121.0-B-1-S Cor. 1", we have to generate:
* CCSDS 121.0-B-1-S Cor. 1
* CCSDS 121.0-B-1 Cor. 1

**Comment by andrew2net** [comment]
For "CCSDS 720.1-G-3-S" generated:

- [CCSDS 720.1-G-3-S](https://github.com/relaton/relaton-data-ccsds/blob/main/data/CCSDS-720-1-G-3-S.yaml)
- [CCSDS 720.1-G-3](https://github.com/relaton/relaton-data-ccsds/blob/main/data/CCSDS-720-1-G-3.yaml)

For "CCSDS 121.0-B-1-S Cor. 1" generated:

- [CCSDS 121.0-B-1-S Cor. 1](https://github.com/relaton/relaton-data-ccsds/blob/main/data/CCSDS-121-0-B-1-S-Cor-1.yaml)
- [CCSDS 121.0-B-1 Cor. 1](https://github.com/relaton/relaton-data-ccsds/blob/main/data/CCSDS-121-0-B-1-Cor-1.yaml)

**Comment by ronaldtse** [comment]
The metadata for Cor is incorrect:
- edition number should be 1 not "1 Cor. 1"
- the Cor document should have a relationship with the base document that the Cor "corrects" it. 
- the base document should also link to the new Cor documents in relations.

**Comment by andrew2net** [comment]
> * the Cor document should have a relationship with the base document that the Cor "corrects" it.

@ronaldtse the Cor document has the [relation](https://github.com/relaton/relaton-data-ccsds/blob/719df6aa9001775370ce5b0b20354475e50d6b34/data/CCSDS-121-0-B-1-S-Cor-1.yaml#L36). Maybe the relation type should be `updates`?

**Comment by ronaldtse** [comment]
@andrew2net `updates` sounds good. We also need to set the reverse `updatedBy` in the base document. Thanks.

**Comment by andrew2net** [comment]
> The metadata for Cor is incorrect:
> 
> * edition number should be 1 not "1 Cor. 1"

https://github.com/relaton/relaton-data-ccsds/blob/0cd7cb348e88b25ac925943bc9ec5147d89403f9/data/CCSDS-121-0-B-1-Cor-1.yaml#L22

> * the Cor document should have a relationship with the base document that the Cor "corrects" it.

https://github.com/relaton/relaton-data-ccsds/blob/0cd7cb348e88b25ac925943bc9ec5147d89403f9/data/CCSDS-121-0-B-1-Cor-1.yaml#L46

> * the base document should also link to the new Cor documents in relations.

https://github.com/relaton/relaton-data-ccsds/blob/0cd7cb348e88b25ac925943bc9ec5147d89403f9/data/CCSDS-121-0-B-1.yaml#L59
